[package]
name = "stribot2"
version = "0.1.0"
authors = ["oleg dashevskii <olegdashevskii@gmail.com>"]

[dependencies]
chrono = "0.4"
clap = "2.32.0"
lazy_static = "1.2.0"
regex = "1"
reqwest = "0.9.5"
rand = "0.6.1"
select = "0.4.2"
